server:
  port: ${SERVER_PORT:8080}

jimmer:
  language: kotlin

spring:
  application:
    name: ksas-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ksas}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

  data:
    redis:
      host: ${REDIS_HOST:localhost:6379}
      password: ${REDIS_PASSWORD:}
