server:
  port: ${SERVER_PORT:8080}
knife4j:
  # 开启增强配置
  # knife4j与springboot3.4.0以上版本不兼容 无法使用增强配置
  enable: false
  # 开启生产环境屏蔽
  production: ${DISABLE_SWAGGER:true}
logging:
  file:
    path: ${LOG_PATH:./logs}
jimmer:
  language: kotlin
  show-sql: ${SHOW_SQL:false}
  pretty-sql: ${SHOW_SQL:false}
  inline-sql-variables: ${SHOW_SQL:false}
  in-list-padding-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info

spring:
  application:
    name: ${APP_NAME:ksas-backend}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ksas}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

  data:
    redis:
      host: ${REDIS_HOST:localhost:6379}
      password: ${REDIS_PASSWORD:}

ksas:
  security:
    auth:
      anon-urls: ${ANON_URLS:/auth/login,/swagger/**,/doc.html,/v3/api-docs/**}
    jwt:
      secret: ${JWT_SECRET:VyHZ8YGV9w94dRw8ixVzJgcoDXqvRokej2339zCxiMIgbgmM}
      access-token-expire: ${ACCESS_TOKEN_EXPIRE_TIME:7d}
      refresh-token-expire: ${REFRESH_TOKEN_EXPIRE_TIME:8d}
