server:
  port: ${KSAS_SERVER_PORT:8080}
knife4j:
  enable: false
  production: ${KSAS_DISABLE_SWAGGER:true}
jimmer:
  language: kotlin
  show-sql: ${KSAS_SHOW_SQL:false}
  pretty-sql: ${KSAS_SHOW_SQL:false}
  inline-sql-variables: ${KSAS_SHOW_SQL:false}
  in-list-padding-enabled: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,prometheus

spring:
  application:
    name: ${KSAS_APP_NAME:ksas-backend}
  datasource:
    url: ${KSAS_DB_URL:jdbc:postgresql://localhost:5432/ksas}
    username: ${KSAS_DB_USERNAME:postgres}
    password: ${KSAS_DB_PASSWORD:postgres}
  flyway:
    enabled: ${KSAS_FLYWAY_ENABLED:false}

  cache:
    redis:
      key-prefix: ${KSAS_CACHE_KEY_PREFIX:ksas-backend:}
      time-to-live: ${KSAS_CACHE_TTL:2d}

  data:
    redis:
      host: ${KSAS_REDIS_HOST:localhost:6379}
      password: ${KSAS_REDIS_PASSWORD:}

ksas:
  security:
    auth:
      anon-urls: ${KSAS_ANON_URLS:/login,/actuator/**,/swagger/**,/doc.html,/v3/api-docs/**}
    jwt:
      secret: ${KSAS_JWT_SECRET:VyHZ8YGV9w94dRw8ixVzJgcoDXqvRokej2339zCxiMIgbgmM}
      access-token-expire: ${KSAS_ACCESS_TOKEN_EXPIRE_TIME:7d}
      refresh-token-expire: ${KSAS_REFRESH_TOKEN_EXPIRE_TIME:8d}
